name: Bug Report
description: Report a software or hardware-related issue
title: "[Bug]: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Please provide as much information as possible to help us reproduce the issue.
  - type: input
    id: version
    attributes:
      label: Software Version
      description: Which version or git commit are you using?
      placeholder: e.g., v1.2.0 or commit a1b2c3d
    validations:
      required: true
  - type: input
    id: hardware
    attributes:
      label: Hardware Device
      description: Specify the board or SoC model.
      placeholder: e.g., Luckfox Pico, RV1106, Raspberry Pi
    validations:
      required: true
  - type: dropdown
    id: soundcard
    attributes:
      label: Sound Card Device
      description: Is it an on-board codec or a USB sound card?
      options:
        - On-board (Internal Codec/I2S)
        - USB Audio Device
        - Other
    validations:
      required: true
  - type: dropdown
    id: bug_type
    attributes:
      label: Bug Category
      description: Select the nature of the issue.
      options:
        - Hardware Bug (e.g., abnormal sound playback, noise, peripheral failure)
        - Software Logic Bug (e.g., authentication error, connection failure, crash)
    validations:
      required: true
  - type: dropdown
    id: rootfs
    attributes:
      label: Rootfs Environment
      description: Select the root filesystem you are running.
      options:
        - Buildroot
        - Busybox
        - Armbian
        - Ubuntu
        - Custom (Please specify in steps)
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Reproduction Steps
      description: How can we reproduce the issue?
      placeholder: |
        1. Power on the device...
        2. Run the command...
        3. See the error...
    validations:
      required: true
  - type: textarea
    id: expected_behavior
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
  - type: checkboxes
    id: confirmations
    attributes:
      label: Confirmations
      options:
        - label: I have checked existing issues and this is not a duplicate.
          required: true
        - label: I have provided system logs (dmesg, journalctl, etc.) if applicable.
          required: false