name: Feature Request
description: Suggest an idea or improvement for this project
title: "[Feature]: "
labels: ["enhancement"]
body:
  - type: textarea
    id: feature_description
    attributes:
      label: Problem Statement
      description: Is your feature request related to a problem? Please describe.
    validations:
      required: true
  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the solution or feature you'd like to see.
    validations:
      required: true